build
failed 4 minutes ago in 16s
Search logs
1s
1s
0s
11s
Run # 1. Buscar la carpeta del proyecto
Proyecto en: .

Welcome to Gradle 9.5.1!

Here are the highlights of this release:
 - Task provenance in reports and failure messages
 - Type-safe accessors for precompiled Kotlin Settings plugins

For more details see https://docs.gradle.org/9.5.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

[Incubating] Problems report is available at: file:///home/runner/work/Escribe-optimax-gaming/Escribe-optimax-gaming/build/reports/problems/problems-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Configuring project ':app' without an existing directory is not allowed. The configured projectDirectory '/home/runner/work/Escribe-optimax-gaming/Escribe-optimax-gaming/app' does not exist, can't be written to or is not a directory.

* Try:
> Make sure the project directory exists and is writable.
> For more information, see https://docs.gradle.org/9.5.1/userguide/multi_project_builds.html#include_existing_projects_only
> Run with --scan to get full insights from a Build Scan (powered by Develocity).

BUILD FAILED in 10s
Error: Process completed with exit code 1.
0s
0s
1s
